### ISSUE TITLE
Throws "this.DragAndDropManager is undefined" when dragging

### ISSUE THREAD

**Issue by torbenrohde** [GreyRook/PIXI.draggable#1]
I can't get it working. When dragging I receive a "this.DragAndDropManager is undefined" at line 1176:

`this.DragAndDropManager.onDrag(this, mouse);`

This is a small reproduction:

```
    var renderer = PIXI.autoDetectRenderer(400, 400,{backgroundColor : 0x1099bb});
    document.body.appendChild(renderer.view);

    // create the root of the scene graph
    var stage = new PIXI.Container();

    // create a texture from an image path
    var texture = PIXI.Texture.fromImage('bunny.png');

    // create a new Sprite using the texture
    var bunny = new PIXI.Sprite(texture);

    // center the sprite's anchor point
    bunny.anchor.x = 0.5;
    bunny.anchor.y = 0.5;

    // move the sprite to the center of the screen
    bunny.position.x = 200;
    bunny.position.y = 150;

    stage.addChild(bunny);

    // start animating
    animate();
    function animate()
    {
        requestAnimationFrame(animate);

        // render the container
        renderer.render(stage);
    }

    //Tried this as well:// var dragAndDrop = new PIXI.DragAndDropManager(PIXI.interaction.InteractionManager)

    var dragMask = new PIXI.Rectangle(0,0,400, 0) //x, y, w, h
    dragMask.interactive = true

    bunny.draggable({
        //Tried this as well:// manager: dragAndDrop,
        axis: 'x',
        containment: dragMask
    }); 
```

Reference for original issue at v2 Github repo:
https://github.com/SebastianNette/PIXI.draggable/issues/4

**Comment by FlorianLudwig** [comment]
I fixed the [example](https://github.com/GreyRook/PIXI.draggable/blob/b3caa712a1d77316d7f62fbf26c88c9f96660de3/examples/demo1.html) in the repository.

You need an interaction manager and a drag and drop manager

```
var interactionManager = new PIXI.interaction.InteractionManager(renderer, {});
var dragAndDropManager = new PIXI.DragAndDropManager(interactionManager);
```

**Comment by FlorianLudwig** [comment]
I think this could be simpler to use, so I opened #2

**Comment by torbenrohde** [comment]
Still can't get it to work. I now get a null reference at PIXI line 7470 (DisplayObject.prototype.updateTransform):
`var pt = this.parent.worldTransform;`

For some reason that I'm unable to determine, it tries to call the `parent` property of the stage that I added my draggable to. Full example:

``` javascript
    var renderer = PIXI.autoDetectRenderer(400, 400,{backgroundColor : 0x1099bb});
    document.body.appendChild(renderer.view);

    // create the root of the scene graph
    var stage = new PIXI.Container();
    stage.idForTrace = "stage"

    // create a texture from an image path
    var texture = PIXI.Texture.fromImage('bunny.png');

    // create a new Sprite using the texture
    var bunny = new PIXI.Sprite(texture);

    // center the sprite's anchor point
    bunny.anchor.x = 0.5;
    bunny.anchor.y = 0.5;

    // move the sprite to the center of the screen
    bunny.position.x = 200;
    bunny.position.y = 150;

    stage.addChild(bunny);

    // start animating
    animate();
    function animate()
    {
        requestAnimationFrame(animate);

        // render the container
        renderer.render(stage);
    }

    var interactionManager = new PIXI.interaction.InteractionManager(renderer, {});
    var dragAndDropManager = new PIXI.DragAndDropManager(interactionManager);

    var dragMask = new PIXI.Rectangle(0,0,400, 0) //x, y, w, h
    dragMask.interactive = true

    bunny.idForTrace = "bunny"
    bunny.draggable({
        manager: dragAndDropManager,
        axis: 'x',
        containment: dragMask
    });
```

**Comment by torbenrohde** [comment]
I got it working by adding this hacky guard clause to DisplayObject.prototype.updateTransform in the PIXI core:

``` javascript
    if (this.parent == null)
    {
        return;
    }
```

It seems to work without any side effects, but maybe I just haven't discovered them yet. Also, this seems to be curing a symptom, rather than the root cause (which I'm unable to determine what is).

**Comment by FabianElsmer** [comment]
The problem is that we tried to generalize the code so that any element can be used as a containment for any draggable element, since this was a requirement for our project.
When the containment and the draggable element aren't both children of the same parent, we have to translate the positions into the local space of their parents:

``` javascript
var local = item.dragElement.parent.toLocal({x:x,y:y});
```

This is no problem when your dragged elements are not directly on the stage (try it, just add your bunny to a container and the container to the stage and it works), but as the stage itself has no parent you cannot use a toLocal function on it.

``` javascript
stage.toLocal({x:0,y:0}) //Always throws an exception
```

**Comment by torbenrohde** [comment]
Ok, I think I will keep my hack for now. But nice to know the background story and possible fix for this.
Thanks.
